#pragma once
#undef MATRIX_ROW_PINS
#undef MATRIX_ROW_PINS_RIGHT
#undef MATRIX_COL_PINS
#undef MATRIX_COL_PINS_RIGHT
#undef ENCODERS_PAD_A
#undef ENCODERS_PAD_B
#undef ENCODERS_PAD_A_RIGHT
#undef ENCODERS_PAD_B_RIGHT
#undef SOFT_SERIAL_PIN
#undef RGB_DI_PIN
#undef SPLIT_HAND_MATRIX_GRID
#define MATRIX_ROW_PINS {GP27, GP26, GP22, GP20}
#define MATRIX_ROW_PINS_RIGHT {GP4, GP5, GP6, GP7}
#define MATRIX_COL_PINS {GP23, GP21, GP9, GP8, GP7, GP6, GP5, GP4}
#define MATRIX_COL_PINS_RIGHT {GP8, GP9, GP21, GP23, GP20, GP22, GP26, GP27}
#define ENCODERS_PAD_A {GP29}
#define ENCODERS_PAD_B {GP28}
#define ENCODERS_PAD_A_RIGHT {GP28}
#define ENCODERS_PAD_B_RIGHT {GP29}
#define SERIAL_USART_TX_PIN GP1
#define RGB_DI_PIN GP0
#define SPLIT_HAND_MATRIX_GRID GP7, GP20
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET // Activates the double-tap behavior
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U // Timeout window in ms in which the double tap can occur.
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED_MASK 0U // Specify a optional status led which
// #define SPLIT_POINTING_ENABLE
// #define POINTING_DEVICE_LEFT
// #define CIRQUE_PINNACLE_CURVED_OVERLAY
#define CIRQUE_PINNACLE_DIAMETER_MM 35
#define CIRQUE_PINNACLE_TAP_ENABLE
#define CIRQUE_PINNACLE_SECONDARY_TAP_ENABLE
#define CIRQUE_PINNACLE_POSITION_MODE CIRQUE_PINNACLE_ABSOLUTE_MODE

#define BATTERY_LEVEL_PIN GP13

#define BLUEFRUIT_LE_RST_PIN GP14
#define BLUEFRUIT_LE_CS_PIN  GP15
#define BLUEFRUIT_LE_IRQ_PIN GP16


#define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE // Enable cursor glide
#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE
#define POINTING_DEVICE_ROTATION_270
// #define CRC8_USE_TABLE
// #define CRC8_OPTIMIZE_SPEED
#ifdef RGBLIGHT_ENABLE
    #define RGBLIGHT_ANIMATIONS
    #define RGBLIGHT_SLEEP
    #define RGBLIGHT_HUE_STEP 5
    #define RGBLIGHT_SAT_STEP 5
#endif
