MCU = RP2040
BOOTLOADER = rp2040
BOARD = GENERIC_PROMICRO_RP2040
WS2812_DRIVER = vendor
SERIAL_DRIVER = vendor
ENCODER_MAP_ENABLE = yes
# RGBLIGHT_ENABLE = yes

MOUSEKEY_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c

# HAPTIC_ENABLE = yes
# HAPTIC_DRIVER += DRV2605L

NKRO_ENABLE = no

BLUETOOTH_ENABLE = yes
BLUETOOTH_DRIVER = BluefruitLE
